[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry-core.masonry.api"

[tool.poetry]
name = "ynab-split-budget"
version = "0.0.3"
authors = ["Daniel Basta <ynabsplitbudget@basta.info>"]
description = "Library to sync You Need A Budget (YNAB) transactions with Splitwise"
readme = "README.md"
license = 'MIT'
packages = [{include = 'ynab_split_budget', from = 'src'}]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = '>=3.8'
pyyaml = '>=6.0'
requests = '>=2.31'

[poetry.urls]
"Homepage" = "https://github.com/dnbasta/ynab-splitwise-sync"
"Bug Tracker" = "https://github.com/dnbasta/ynab-splitwise-sync/issues"
