[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ynab-split-budget"
version = "0.0.1"
authors = [
  { name="Daniel Basta", email="ynabsplitbudget@basta.info" },
]
description = "Library to sync You Need A Budget (YNAB) transactions with Splitwise"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pyyaml",
    "requests"
]

[project.urls]
"Homepage" = "https://github.com/dnbasta/ynab-splitwise-sync"
"Bug Tracker" = "https://github.com/dnbasta/ynab-splitwise-sync/issues"